type StateT = {
    user: UserT,
    project: ProjectReducedT,
    sidebarCollapsed: boolean,
    cqSelectedGroup: { id: string, name: string },
    cqUnifiedView: boolean,
    cqSelectedTopicIds: string[],
    cqSearchQuery: string,
    cqFilters: import('../utils/cqFilters').CqFilters,
    cqFiltersOpen: boolean,
    cqShowLastComment: boolean,
    cqSort: import('../utils/cqSort').CqSort,
    cqExportFormat: 'markdown' | 'csv',
    cqExportFields: string[],
}